apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "localservice.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    nginx.ingress.kubernetes.io/proxy-read-timeout: 300s
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ .Values.ingressHost }}
    http:
      paths:
      - backend:
          serviceName: {{ include "localservice.fullname" . }}
          servicePort: 80
        path: /{{ .Values.pathPart }}/(.+)
